apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: arkar20/ticketing-payment
    context: ticketing-payment
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile

  - image: arkar20/ticketing-auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
      
  - image: arkar20/ticketing-expiration
    context: ticketing-expiration
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
      
  - image: arkar20/ticketing-tickets
    context: tickets
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile

  - image: arkar20/ticketing-client
    context: client
    sync:
      manual:
      - src: /**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
      
  - image: arkar20/ticketing-order
    context: order
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}