apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image:  arkar20/ticketing-auth
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                  name: jwt-secret
                  key:  JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: 3000

