apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: arkar20/ticketing-order
        env:
          - name: NATS_CLUSTER_ID
            value: "ticketing"
          - name: NATS_URL
            value: "http://nats-srv:4222"
          - name: NATS_CLIENT_ID
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: MONGO_URL
            value: "mongodb://order-mongo-srv:27017/order"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                  name: jwt-secret
                  key:  JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: order-srv
spec:
  selector:
    app: order
  ports:
  - port: 3000
    targetPort: 3000

