apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-payment-depl
spec:
  selector:
    matchLabels:
      app: ticketing-payment
  template:
    metadata:
      labels:
        app:  ticketing-payment
    spec:
      containers:
      - name:  ticketing-payment
        image: arkar20/ticketing-payment
        env:
          - name: NATS_CLUSTER_ID
            value: "ticketing"
          - name: NATS_URL
            value: "http://nats-srv:4222"
          - name: NATS_CLIENT_ID
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: MONGO_URL
            value: "mongodb://payment-mongo-srv:27017/payments"
          - name: STRIPE_SECRET 
            valueFrom: 
              secretKeyRef:
                name: stripe-secret 
                key: STRIPE_SECRET
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                  name: jwt-secret
                  key:  JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payment-srv
spec:
  selector:
    app: ticketing-payment
  ports:
  - port: 3000
    targetPort: 3000

